version: '3.8'

services:
    app: 
        build: 
            context: ./client
            dockerfile: Dockerfile
        image: kanjiapp
        stdin_open: true
        command: npm start
        volumes:
            - ./client/src:/client/src
        environment: 
            - CHOKIDAR_USEPOLLING=true
        ports:
        - 3000:3000
volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local